version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: testmanager_postgres
    restart: always
    environment:
      POSTGRES_DB: testmanager_db
      POSTGRES_USER: testmanager_user
      POSTGRES_PASSWORD: testmanager_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - testmanager_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testmanager_user -d testmanager_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: testmanager_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@testmanager.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
      PGADMIN_DEFAULT_SERVER: 'testmanager_postgres'
      PGADMIN_DEFAULT_SERVER_PORT: '5432'
      PGADMIN_DEFAULT_SERVER_USERNAME: 'testmanager_user'
      PGADMIN_DEFAULT_SERVER_PASSWORD: 'testmanager_password'
      PGADMIN_DEFAULT_SERVER_DATABASE: 'testmanager_db'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
      - ./pgadmin/pgpass:/pgpass:ro
    networks:
      - testmanager_network
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  testmanager_network:
    driver: bridge 